# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7964c46ff5b017b0fb5541d11946f0ef"
name = "inventory-auto-sync-v2"
application_url = "https://inventory-auto-sync-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locations"

[auth]
redirect_urls = [
  "https://inventory-auto-sync-production.up.railway.app/auth/callback",
  "https://inventory-auto-sync-production.up.railway.app/api/auth/callback"
]
